apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-sourcegraph
  namespace: prod
spec:
  selector:
    matchLabels:
      app: gitlab-sourcegraph
  replicas: 1
  template:
    metadata:
      labels:
        app: gitlab-sourcegraph
    spec:
      containers:
        - name: gitlab-sourcegraph
          image: sourcegraph/server:3.39.1
          imagePullPolicy: Always
          # securityContext:
          #   runAsUser: 1000
          #   runAsGroup: 1000
          ports:
            - name: main
              containerPort: 7080
            - name: additional
              containerPort: 3070
          resources:
            requests:
              memory: "4Gi"
              cpu: "4000m"
            limits:
              memory: "8Gi"
              cpu: "6000m"
          env:
            - name: TZ
              value: Europe/Kiev
          volumeMounts:
            - name: nfs-mount
              mountPath: /etc/sourcegraph
              subPath: config
            - name: nfs-mount
              mountPath: /var/opt/sourcegraph
              subPath: data                          
      volumes:
        - name: nfs-mount
          persistentVolumeClaim:
            claimName: pvc-nfs-gitlab-sourcegraph