apiVersion: v1
kind: Service
metadata:
  name: gitlab-sourcegraph
  namespace: prod
spec:
  type: NodePort
  ports:
    - name: http
      port: 7080
      targetPort: 7080
      nodePort: 30003
    - name: additional
      port: 3370
      targetPort: 3370
      nodePort: 30004
  selector:
    app: gitlab-sourcegraph
