apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-kkoltsov
  namespace: dev
  labels:
    app: postgres-kkoltsov
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi