apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-nifi-rtn
  namespace: dmp-rtn-dev
  labels:
    app: dmp-cep-dev
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500G